# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Weka Trace Replay Data Generator.

This module provides a data generator that replays Weka KV-cache-tester traces
(e.g., from Hugging Face semianalysisai/cc-traces-weka-*).

KV-Cache Fidelity & Prompt Reconstruction
-----------------------------------------
Weka traces record conversation sessions as a sequence of block hash IDs (representing fixed-size
token blocks, e.g. 16 tokens/block). They do not store the original raw text prompts or completions.
To evaluate the KV-cache scheduler/performance of a target server under identical hit/miss conditions,
the generator must reconstruct conversation prompt text that tokenizes to the exact sequence of block
hashes recorded in the trace.

1. Turn-by-Turn Reconstructor:
   For every request (turn) in a session, the generator uses a deterministic `HashIdRandomGenerator`
   seeded with a combination of base seed, conversation ID, and block hash ID. It samples words from
   a static, public domain corpus (Shakespeare) to construct the prompt and expected assistant response text.
   This guarantees that if the same block hash ID is visited on different turns or worker processes,
   it always maps to the exact same text tokens, producing identical KV-cache keys on the server.

2. Longest Common Prefix (LCP) and Branching:
   During multi-turn conversations, the user may shift topics or backtrack. The generator compares
   the block hashes of consecutive turns (`longest_common_prefix`).
   - If Turn 1 has hashes [H1, H2, H3] and Turn 2 has [H1, H2, H4], the LCP is 2.
   - The reconstructor uses this LCP to rewind the conversation history back to the end of block 2 (H2),
     evicting the text for block H3, before appending the new prompt block H4.
   - This ensures prompt-cache structural alignment matches the trace exactly.

3. History Substitution Rationale:
   The generator pre-reconstructs assistant response text based on the output token lengths in the trace.
   During live replay, the actual text generated by the server is discarded for the purpose of history building.
   Instead, the pre-reconstructed assistant text is appended to construct subsequent turn prompts.

   - Why? If the live model deviates by even 1 token in output length, it shifts the start index of the next
     user prompt. Because KV-cache blocks are aligned on fixed boundaries, this 1-token shift would cause a
     100% cache miss on all subsequent user prompt blocks.
   - History substitution preserves the exact token offsets and boundaries, guaranteeing 100% KV-cache alignment
     under deterministic (temperature=0) benchmarks. Caveat is that this is not always possible when benchmarking
     different models. But this approach is preserved so we can resemble the KV cache tester approach for this
     replay which is what we are trying to emulate.
"""

from dataclasses import dataclass
import hashlib
import json
import logging
import math
from pathlib import Path
import random
from typing import Any, Dict, List, Literal, Optional, Tuple, Union, Annotated
from multiprocessing.managers import SyncManager

from huggingface_hub import hf_hub_download
from pydantic import BaseModel, Field

from inference_perf.config import APIConfig, DataConfig
from inference_perf.datagen.replay_graph_session_datagen import (
    ReplaySession,
    ReplayGraphSessionGeneratorBase,
    ReplaySessionEvent,
)
from inference_perf.datagen.otel_trace_to_replay_graph import (
    RawCall,
    build_graph,
)
from inference_perf.datagen.replay_graph_types import ReplayMessage, GraphEvent, GraphCall, InputSegment, ReplayGraph
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)

_global_generator = None


def _build_session_worker_task_global(trace_and_index: Tuple[Any, int]) -> Optional[ReplaySession]:
    import sys

    trace, trace_index = trace_and_index
    global _global_generator
    if _global_generator is None:
        print("Worker error: _global_generator is None!", file=sys.stderr)
        return None
    try:
        res = _global_generator._reconstruct_raw_calls(trace)
        if not res:
            return None
        raw_calls, warmup_event = res
        from inference_perf.datagen.otel_trace_to_replay_graph import build_graph

        graph = build_graph(raw_calls, source_file=f"weka_trace_{trace.id}")
        if _global_generator.weka_config.ignore_trace_delays:
            for ev in graph.events.values():
                ev.wait_ms = 0
        if _global_generator.weka_config.warmup_cache_priming and warmup_event is not None:
            _global_generator._insert_warmup_event_into_graph(graph, warmup_event)
            warmup_event = None
        session_id = f"wekatrace{trace_index}_{trace.id}"
        return ReplaySession(
            session_id=session_id,
            source_id=trace.id,
            session_index=trace_index,
            graph=graph,
            warmup_event=warmup_event,
        )
    except Exception as e:
        print(f"Worker failed to process Weka trace {trace.id}: {e}", file=sys.stderr)
        return None


# =============================================================================
# Weka Trace Pydantic Models
# =============================================================================


class WekaNormalRequest(BaseModel):
    t: float
    type: Literal["n"]
    model: str
    input_length: int = Field(alias="in")
    output_length: int = Field(alias="out")
    hash_ids: List[int] = Field(default_factory=list)
    api_time: Optional[float] = None
    think_time: Optional[float] = None


class WekaStreamingRequest(BaseModel):
    t: float
    type: Literal["s"]
    model: str
    input_length: int = Field(alias="in")
    output_length: int = Field(alias="out")
    hash_ids: List[int] = Field(default_factory=list)
    api_time: Optional[float] = None
    think_time: Optional[float] = None
    ttft: Optional[float] = None


class WekaSubagentEntry(BaseModel):
    t: float
    type: Literal["subagent"]
    agent_id: str
    subagent_type: str
    duration_ms: Optional[int] = None
    requests: List[WekaNormalRequest] = Field(default_factory=list)
    tool_tokens: int = 0
    system_tokens: int = 0


WekaRequest = Annotated[Union[WekaNormalRequest, WekaStreamingRequest, WekaSubagentEntry], Field(discriminator="type")]


class WekaTrace(BaseModel):
    id: str
    models: List[str]
    block_size: int
    tool_tokens: int = 0
    system_tokens: int = 0
    requests: List[WekaRequest]


# =============================================================================
# Timeline Timing & Warping
# =============================================================================


@dataclass(frozen=True)
class _RequestTiming:
    timestamp_seconds: float
    delay_ms: Optional[float]


@dataclass(frozen=True)
class _IdleGap:
    raw_start: float
    raw_end: float
    shift_before: float
    cap_seconds: float
    excess_seconds: float


class _IdleGapTimeWarp:
    """Compresses request-start gaps in a trace and maps raw seconds to adjusted seconds."""

    def __init__(self, request_starts: List[float], cap_seconds: float):
        self._gaps: List[_IdleGap] = []
        sorted_starts = sorted(request_starts)
        if not sorted_starts:
            return

        prev_start = sorted_starts[0]
        cumulative_shift = 0.0
        for start in sorted_starts[1:]:
            gap_seconds = start - prev_start
            if gap_seconds > cap_seconds:
                excess = gap_seconds - cap_seconds
                self._gaps.append(
                    _IdleGap(
                        raw_start=prev_start,
                        raw_end=start,
                        shift_before=cumulative_shift,
                        cap_seconds=cap_seconds,
                        excess_seconds=excess,
                    )
                )
                cumulative_shift += excess
            prev_start = start

    def map(self, t_seconds: float) -> float:
        shift = 0.0
        for gap in self._gaps:
            if t_seconds < gap.raw_start:
                return t_seconds - gap.shift_before
            if t_seconds < gap.raw_end:
                local = t_seconds - gap.raw_start
                if local <= gap.cap_seconds:
                    return t_seconds - gap.shift_before
                return gap.raw_start - gap.shift_before + gap.cap_seconds
            shift = gap.shift_before + gap.excess_seconds
        return t_seconds - shift


# =============================================================================
# Hash-ID Based Prompt Synthesis
# =============================================================================


class HashIdRandomGenerator:
    """Deterministic random generator scoped per (trace_id, hash_id)."""

    def __init__(self, base_seed: int):
        self.base_seed = base_seed
        self._trace_id: str = ""
        self._rng = random.Random()

    def set_trace_id(self, trace_id: str) -> None:
        self._trace_id = trace_id

    def reseed_for_hash_id(self, hash_id: int) -> None:
        seed_bytes = hashlib.sha256(f"{self.base_seed}:{self._trace_id}:{hash_id}".encode()).digest()
        self._rng.seed(int.from_bytes(seed_bytes[:8], "big"))

    def randrange(self, stop: int) -> int:
        return self._rng.randrange(stop)

    def choice(self, seq: list[Any]) -> Any:
        return self._rng.choice(seq)


def sample_tokens_from_corpus(
    corpus: List[int],
    num_tokens: int,
    rng_to_use: HashIdRandomGenerator,
    sep_token: Optional[int] = None,
) -> List[int]:
    """Sample tokens from the pre-tokenized corpus using the provided RNG."""
    corpus_len = len(corpus)
    tokens: List[int] = []

    if sep_token is not None:
        tokens.append(sep_token)
        num_tokens -= 1

    start = rng_to_use.randrange(corpus_len)
    end = start + num_tokens

    if end <= corpus_len:
        tokens.extend(corpus[start:end])
    else:
        tokens.extend(corpus[start:])
        tokens.extend(corpus[: end - corpus_len])

    return tokens


# =============================================================================
# Conversation Reconstructor
# =============================================================================


@dataclass
class RoleSegment:
    role: Literal["system", "user", "assistant"]
    block_start: int
    block_count: int
    tokens: List[int]
    content: str
    token_count: int


def longest_common_prefix(prev_hash_ids: List[int], curr_hash_ids: List[int]) -> int:
    n = min(len(prev_hash_ids), len(curr_hash_ids))
    for i in range(n):
        if prev_hash_ids[i] != curr_hash_ids[i]:
            return i
    return n


def truncate_synth_buf_at_block(
    segments: List[RoleSegment],
    target_blocks: int,
    block_size: int,
    decode_tokens_to_text: Any,
    count_tokens: Any,
    prev_partial_tail: int = 0,
) -> Optional[int]:
    if target_blocks <= 0:
        had_segments = len(segments) > 0
        segments.clear()
        return 0 if had_segments else None

    cursor = 0
    for i, seg in enumerate(segments):
        if cursor + seg.block_count < target_blocks:
            cursor += seg.block_count
            continue
        if cursor + seg.block_count == target_blocks:
            disturbed: Optional[int] = None
            if prev_partial_tail > 0 and len(seg.tokens) > 0:
                stripped_n = min(prev_partial_tail, len(seg.tokens))
                seg.tokens = seg.tokens[:-stripped_n]
                seg.content = decode_tokens_to_text(seg.tokens)
                seg.token_count = count_tokens(seg.content)
                disturbed = i
            deleted_past_boundary = i + 1 < len(segments)
            del segments[i + 1 :]
            if disturbed is None and deleted_past_boundary:
                disturbed = i + 1
            return disturbed
        if cursor == target_blocks:
            del segments[i:]
            return i
        kept_blocks = target_blocks - cursor
        kept_tokens_n = min(len(seg.tokens), kept_blocks * block_size)
        seg.block_count = kept_blocks
        seg.tokens = seg.tokens[:kept_tokens_n]
        seg.content = decode_tokens_to_text(seg.tokens)
        seg.token_count = count_tokens(seg.content)
        del segments[i + 1 :]
        return i
    return None


class ConversationReconstructor:
    """Reconstructs turn-by-turn prompts and completions deterministically."""

    def __init__(
        self,
        block_size: int,
        decode_block_tokens: Any,
        sample_partial_tail_tokens: Any,
        decode_tokens_to_text: Any,
        count_tokens: Any,
    ):
        self.block_size = block_size
        self.decode_block_tokens = decode_block_tokens
        self.sample_partial_tail_tokens = sample_partial_tail_tokens
        self.decode_tokens_to_text = decode_tokens_to_text
        self.count_tokens = count_tokens
        self._segments: List[RoleSegment] = []
        self._last_disturbance_at: Optional[int] = None

    def init_turn_0(
        self,
        hash_ids: List[int],
        in_tokens: int,
        tool_tokens: int,
        system_tokens: int,
        seed: str,
    ) -> None:
        bs = self.block_size
        m_full = in_tokens // bs
        partial_tail_tokens_n = in_tokens - m_full * bs
        covered_blocks = min(m_full, len(hash_ids))
        missing_block_tokens = (m_full - covered_blocks) * bs

        cursor = 0
        segs: List[RoleSegment] = []

        if tool_tokens > 0 or system_tokens > 0:
            prefix_tokens = tool_tokens + system_tokens
            prefix_blocks = math.ceil(prefix_tokens / bs)
            if prefix_blocks > 0:
                if prefix_blocks > len(hash_ids):
                    # Fallback or clamp if missing prefix hash blocks
                    prefix_blocks = len(hash_ids)
                if prefix_blocks > 0:
                    seg_tokens = self.decode_block_tokens(hash_ids[cursor : cursor + prefix_blocks])
                    content = self.decode_tokens_to_text(seg_tokens)
                    segs.append(
                        RoleSegment(
                            role="system",
                            block_start=cursor,
                            block_count=prefix_blocks,
                            tokens=seg_tokens,
                            content=content,
                            token_count=self.count_tokens(content),
                        )
                    )
                    cursor += prefix_blocks

        user_blocks = covered_blocks - cursor
        user_tokens = self.decode_block_tokens(hash_ids[cursor : cursor + user_blocks])
        synth_tail_n = missing_block_tokens + partial_tail_tokens_n
        if synth_tail_n > 0:
            user_tokens.extend(self.sample_partial_tail_tokens(synth_tail_n, seed))
        content = self.decode_tokens_to_text(user_tokens)
        segs.append(
            RoleSegment(
                role="user",
                block_start=cursor,
                block_count=user_blocks,
                tokens=user_tokens,
                content=content,
                token_count=self.count_tokens(content),
            )
        )

        self._segments = segs
        self._last_disturbance_at = None

    def advance_turn(
        self,
        prev_hash_ids: List[int],
        prev_in_tokens: int,
        prev_out_tokens: int,
        curr_hash_ids: List[int],
        curr_in_tokens: int,
        seed: str,
    ) -> None:
        bs = self.block_size
        m_curr = len(curr_hash_ids)
        m_curr_full = curr_in_tokens // bs
        missing_block_tokens = max(0, (m_curr_full - m_curr) * bs)
        lcp = longest_common_prefix(prev_hash_ids, curr_hash_ids)
        prev_partial_tail = prev_in_tokens % bs

        truncate_disturbance = truncate_synth_buf_at_block(
            self._segments,
            lcp,
            bs,
            decode_tokens_to_text=self.decode_tokens_to_text,
            count_tokens=self.count_tokens,
            prev_partial_tail=prev_partial_tail,
        )
        self._last_disturbance_at = truncate_disturbance

        new_blocks = curr_hash_ids[lcp:m_curr]
        new_partial_tail_n = curr_in_tokens % bs
        new_region_tokens = self.decode_block_tokens(new_blocks)
        synth_tail_n = missing_block_tokens + new_partial_tail_n
        if synth_tail_n > 0:
            new_region_tokens.extend(self.sample_partial_tail_tokens(synth_tail_n, seed))
        new_blocks_count = m_curr - lcp

        asst_blocks_target = math.ceil(prev_out_tokens / bs) if prev_out_tokens > 0 else 0
        if not any(seg.role == "user" for seg in self._segments):
            asst_blocks_target = 0
        asst_blocks = min(asst_blocks_target, new_blocks_count)
        asst_emit_size = asst_blocks * bs

        cursor = lcp
        if asst_blocks > 0:
            asst_tokens = new_region_tokens[:asst_emit_size]
            content = self.decode_tokens_to_text(asst_tokens)
            self._segments.append(
                RoleSegment(
                    role="assistant",
                    block_start=cursor,
                    block_count=asst_blocks,
                    tokens=asst_tokens,
                    content=content,
                    token_count=self.count_tokens(content),
                )
            )
            cursor += asst_blocks

        user_blocks = new_blocks_count - asst_blocks
        user_tokens = new_region_tokens[asst_emit_size:]
        if len(user_tokens) > 0:
            content = self.decode_tokens_to_text(user_tokens)
            self._segments.append(
                RoleSegment(
                    role="user",
                    block_start=cursor,
                    block_count=user_blocks,
                    tokens=user_tokens,
                    content=content,
                    token_count=self.count_tokens(content),
                )
            )

    def snapshot_messages(self) -> List[Dict[str, Any]]:
        return [{"role": s.role, "content": s.content, "token_count": s.token_count} for s in self._segments]


# =============================================================================
# Intermediate Reconstruction Plan Representations
# =============================================================================


@dataclass
class _ParentPlan:
    trace_id: str
    normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]]
    subagents: List[Tuple[int, WekaSubagentEntry]]
    block_size: int


@dataclass
class _ChildPlan:
    session_id: str
    parent_trace_id: str
    subagent_index: int
    entry: WekaSubagentEntry
    stream_index: int
    stream_requests: List[WekaNormalRequest]
    block_size: int


@dataclass
class _TraceIdleTiming:
    parent_by_outer_idx: Dict[int, _RequestTiming]
    child_by_session_request: Dict[Tuple[str, int], _RequestTiming]
    subagent_end_by_outer_idx: Dict[int, float]
    subagent_start_by_outer_idx: Dict[int, float]


def _sa_end_seconds(entry: WekaSubagentEntry) -> float:
    duration = entry.duration_ms or 0
    return entry.t + duration / 1000.0


def _subagent_request_absolute_t(entry: WekaSubagentEntry, req: WekaNormalRequest) -> float:
    if req.t + 1e-6 < entry.t:
        return entry.t + req.t
    return req.t


def _pack_into_streams(requests: List[WekaNormalRequest]) -> List[List[WekaNormalRequest]]:
    sorted_reqs = sorted(requests, key=lambda r: r.t)
    streams: List[List[WekaNormalRequest]] = []
    stream_ends: List[float] = []
    for r in sorted_reqs:
        r_end = r.t + (r.api_time or 0.0)
        placed = False
        for i, end in enumerate(stream_ends):
            if end <= r.t:
                streams[i].append(r)
                stream_ends[i] = r_end
                placed = True
                break
        if not placed:
            streams.append([r])
            stream_ends.append(r_end)
    return streams


def _build_trace_idle_timing(
    plan: _ParentPlan,
    child_plans: List[_ChildPlan],
    cap_seconds: float,
) -> _TraceIdleTiming:
    if cap_seconds <= 0:
        parent_by_outer_idx = {}
        prev_t = None
        for outer_idx, req in plan.normals:
            delay_ms: Optional[float] = None if prev_t is None else (req.t - prev_t) * 1000.0
            parent_by_outer_idx[outer_idx] = _RequestTiming(req.t, delay_ms)
            prev_t = req.t

        child_by_session_request = {}
        child_plans_for_trace = [cp for cp in child_plans if cp.parent_trace_id == plan.trace_id]
        for cp in child_plans_for_trace:
            prev_child_t = None
            for k, req in enumerate(cp.stream_requests):
                t = _subagent_request_absolute_t(cp.entry, req)
                delay_ms = None if prev_child_t is None else (t - prev_child_t) * 1000.0
                child_by_session_request[(cp.session_id, k)] = _RequestTiming(t, delay_ms)
                prev_child_t = t

        subagent_end_by_outer_idx = {outer_idx: _sa_end_seconds(entry) for outer_idx, entry in plan.subagents}
        subagent_start_by_outer_idx = {outer_idx: entry.t for outer_idx, entry in plan.subagents}
        return _TraceIdleTiming(
            parent_by_outer_idx=parent_by_outer_idx,
            child_by_session_request=child_by_session_request,
            subagent_end_by_outer_idx=subagent_end_by_outer_idx,
            subagent_start_by_outer_idx=subagent_start_by_outer_idx,
        )

    request_starts: List[float] = [req.t for _, req in plan.normals]

    # Filter child plans for this trace
    child_plans_for_trace = [cp for cp in child_plans if cp.parent_trace_id == plan.trace_id]
    for cp in child_plans_for_trace:
        for req in cp.stream_requests:
            request_starts.append(_subagent_request_absolute_t(cp.entry, req))

    warp = _IdleGapTimeWarp(request_starts, cap_seconds)
    parent_by_outer_idx = {}
    prev_t = None
    for outer_idx, req in plan.normals:
        t = warp.map(req.t)
        delay_ms = None if prev_t is None else (t - prev_t) * 1000.0
        parent_by_outer_idx[outer_idx] = _RequestTiming(t, delay_ms)
        prev_t = t

    child_by_session_request = {}
    for cp in child_plans_for_trace:
        prev_child_t = None
        for k, req in enumerate(cp.stream_requests):
            t = warp.map(_subagent_request_absolute_t(cp.entry, req))
            delay_ms = None if prev_child_t is None else (t - prev_child_t) * 1000.0
            child_by_session_request[(cp.session_id, k)] = _RequestTiming(t, delay_ms)
            prev_child_t = t

    subagent_end_by_outer_idx = {outer_idx: warp.map(_sa_end_seconds(entry)) for outer_idx, entry in plan.subagents}
    subagent_start_by_outer_idx = {outer_idx: warp.map(entry.t) for outer_idx, entry in plan.subagents}
    return _TraceIdleTiming(
        parent_by_outer_idx=parent_by_outer_idx,
        child_by_session_request=child_by_session_request,
        subagent_end_by_outer_idx=subagent_end_by_outer_idx,
        subagent_start_by_outer_idx=subagent_start_by_outer_idx,
    )


_TITLE_GEN_MAX_OUTPUT_TOKENS = 64

def _split_off_preamble(
    normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]],
) -> Tuple[List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]], List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]]]:
    if len(normals) < 2:
        return [], normals
    ordered = sorted(normals, key=lambda item: (item[1].t if hasattr(item[1], "t") and item[1].t is not None else 0, item[0]))
    outer_idx, req = ordered[0]
    if not req.hash_ids:
        return [], normals
    rest = ordered[1:]
    if any(longest_common_prefix(req.hash_ids, other.hash_ids) > 0 for _, other in rest if other.hash_ids):
        return [], normals
    if req.output_length > _TITLE_GEN_MAX_OUTPUT_TOKENS:
        other_blocks: set[int] = set()
        for _, other in rest:
            other_blocks.update(other.hash_ids)
        if not other_blocks.isdisjoint(req.hash_ids):
            return [], normals
    return [(outer_idx, req)], sorted(rest, key=lambda item: item[0])

# =============================================================================
# WekaTraceReplayDataGenerator Class
# =============================================================================


class WekaTraceReplayDataGenerator(ReplayGraphSessionGeneratorBase):
    """Data generator that replays LLM requests from Weka trace files."""

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
        worker_mode: bool = False,
    ) -> None:
        if not hasattr(config, "weka_trace_replay") or config.weka_trace_replay is None:
            raise ValueError("weka_trace_replay configuration is required for WekaTraceReplayDataGenerator")

        self.weka_config = config.weka_trace_replay

        # Pass the replay config to the parent class
        super().__init__(
            api_config,
            config,
            tokenizer,
            mp_manager=mp_manager,
            base_seed=base_seed,
            num_workers=num_workers,
            replay_config=self.weka_config,
        )

        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42

        # Initialize deterministic prompt corpus
        if self.tokenizer is None:
            raise ValueError("Tokenizer is required for WekaTraceReplayDataGenerator")

        if self.config and self.config.corpus_file_path:
            corpus_path = Path(self.config.corpus_file_path)
        else:
            corpus_path = Path(__file__).resolve().parents[1] / "assets" / "shakespeare.txt"

        if not corpus_path.is_file():
            raise FileNotFoundError(f"Prompt corpus file not found: {corpus_path}")

        corpus_text = corpus_path.read_text(encoding="utf-8")
        logger.info(f"Loaded prompt corpus from: {corpus_path} ({len(corpus_text)} chars)")

        base_prompt = "Pick as many lines as you can from these poem lines:\n"
        self._tokenized_corpus = self.tokenizer.get_tokenizer().encode(base_prompt + corpus_text)
        self._corpus_size = len(self._tokenized_corpus)

        self._hash_id_rng = HashIdRandomGenerator(self.base_seed)
        self._cache: Dict[int, List[int]] = {}

        if not worker_mode:
            import pickle

            cache_file = Path("/workspace/weka_sessions_cache.pkl")
            if cache_file.is_file():
                logger.info("Loading pre-built session graphs from cache file...")
                try:
                    with open(cache_file, "rb") as f:
                        sessions = pickle.load(f)
                    logger.info(f"Successfully loaded {len(sessions)} sessions from cache")
                except Exception as e:
                    logger.error(f"Failed to load sessions from cache: {e}. Rebuilding...")
                    traces = self._load_weka_traces()
                    sessions = self._build_sessions_from_traces(traces)
                    # Try to save to cache
                    try:
                        with open(cache_file, "wb") as f:
                            pickle.dump(sessions, f)
                    except Exception as e_save:
                        logger.error(f"Failed to cache built sessions: {e_save}")
            else:
                # Load all WekaTrace records
                traces = self._load_weka_traces()
                sessions = self._build_sessions_from_traces(traces)
                # Try to save to cache
                try:
                    logger.info("Saving built session graphs to cache file...")
                    with open(cache_file, "wb") as f:
                        pickle.dump(sessions, f)
                    logger.info("Successfully cached built sessions")
                except Exception as e:
                    logger.error(f"Failed to cache built sessions: {e}")

            self.initialize_sessions(sessions)

    def _load_weka_traces(self) -> List[WekaTrace]:
        """Loads traces from directories, files, or Hugging Face dataset."""
        raw_traces: List[WekaTrace] = []

        if self.weka_config.trace_directory:
            trace_dir = Path(self.weka_config.trace_directory)
            if not trace_dir.exists() or not trace_dir.is_dir():
                raise ValueError(f"Trace directory does not exist or is not a directory: {trace_dir}")
            files = sorted(trace_dir.glob("*.json"))
            if not files:
                raise ValueError(f"No JSON files found in {trace_dir}")

            for f in files:
                try:
                    blob = json.loads(f.read_text(encoding="utf-8"))
                    raw_traces.append(WekaTrace.model_validate(blob))
                except Exception as e:
                    logger.error(f"Failed to load trace {f.name}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        elif self.weka_config.trace_files:
            for path in self.weka_config.trace_files:
                f = Path(path)
                if not f.is_file():
                    raise ValueError(f"Trace file does not exist: {path}")
                try:
                    blob = json.loads(f.read_text(encoding="utf-8"))
                    raw_traces.append(WekaTrace.model_validate(blob))
                except Exception as e:
                    logger.error(f"Failed to load trace {f.name}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        elif self.weka_config.hf_dataset_path:
            repo_id = self.weka_config.hf_dataset_path
            if isinstance(repo_id, dict):
                repo_id = repo_id["path"]
            logger.info(f"Downloading Weka traces from Hugging Face dataset: {repo_id}")
            try:
                # Use raw file download to bypass buggy Feature-type validation in datasets
                local_path = hf_hub_download(repo_id=repo_id, filename="traces.jsonl", repo_type="dataset")
                logger.info(f"Trace file downloaded to {local_path}")

                with open(local_path, "r", encoding="utf-8") as file_stream:
                    for line_idx, line in enumerate(file_stream):
                        if line_idx >= self.weka_config.num_dataset_entries:
                            break
                        if line.strip():
                            try:
                                blob = json.loads(line)
                                raw_traces.append(WekaTrace.model_validate(blob))
                            except Exception as e:
                                logger.error(f"Failed to validate row {line_idx}: {e}")
                                if not self.weka_config.skip_invalid_files:
                                    raise
            except Exception as e:
                raise ValueError(f"Failed to load Hugging Face dataset {repo_id}: {e}") from e

        # Ensure unique trace IDs
        unique_traces: Dict[str, WekaTrace] = {}
        for trace in raw_traces:
            if trace.id in unique_traces:
                raise ValueError(f"Duplicate trace ID found: {trace.id}")
            unique_traces[trace.id] = trace

        return list(unique_traces.values())

    def _build_sessions_from_traces(self, traces: List[WekaTrace]) -> List[ReplaySession]:
        sessions: List[ReplaySession] = []

        if self.num_workers > 1:
            import multiprocessing as mp

            logger.info(f"Building {len(traces)} trace sessions in parallel using {self.num_workers} processes")

            global _global_generator
            _global_generator = self

            tasks = [(trace, idx) for idx, trace in enumerate(traces)]
            ctx = mp.get_context("fork")
            with ctx.Pool(processes=self.num_workers) as pool:
                results = pool.map(_build_session_worker_task_global, tasks)

            for res in results:
                if res is not None:
                    sessions.append(res)
        else:
            logger.info(f"Building {len(traces)} trace sessions sequentially")
            for trace_index, trace in enumerate(traces):
                try:
                    calls_and_warmup = self._reconstruct_raw_calls(trace)
                    if not calls_and_warmup:
                        continue
                    raw_calls, warmup_event = calls_and_warmup

                    graph = build_graph(raw_calls, source_file=f"weka_trace_{trace.id}")
                    if self.weka_config.warmup_cache_priming and warmup_event is not None:
                        self._insert_warmup_event_into_graph(graph, warmup_event)
                        warmup_event = None

                    # Make session ID unique per trace run
                    session_id = f"wekatrace{trace_index}_{trace.id}"
                    sessions.append(
                        ReplaySession(
                            session_id=session_id,
                            source_id=trace.id,
                            session_index=trace_index,
                            graph=graph,
                            warmup_event=warmup_event,
                        )
                    )
                except Exception as e:
                    logger.error(f"Failed to process Weka trace {trace.id}: {e}")
                    if not self.weka_config.skip_invalid_files:
                        raise

        # Shuffle sessions for stress testing
        random.seed(self.base_seed)
        random.shuffle(sessions)
        return sessions

    def _truncate_text_to_len(self, text: str, max_tokens: int) -> str:
        tokens = self.tokenizer.get_tokenizer().encode(text)
        if len(tokens) <= max_tokens:
            return text
        truncated_tokens = tokens[:max_tokens]
        decoded = self.tokenizer.get_tokenizer().decode(truncated_tokens)
        return decoded if isinstance(decoded, str) else " ".join(decoded)

    def _clamp_messages_to_model_limit(self, messages: List[Dict[str, Any]], max_out: int) -> List[Dict[str, str]]:
        if not self.weka_config.max_model_len or self.weka_config.forbid_input_truncation:
            return [{"role": m["role"], "content": m["content"]} for m in messages]
            
        max_in = self.weka_config.max_model_len - max_out - 8192
        if max_in <= 0:
            return [{"role": m["role"], "content": m["content"]} for m in messages]
            
        # 1. Identify system prompt
        sys_msg = None
        start_idx = 0
        sys_len = 0
        if messages and messages[0].get("role") == "system":
            sys_msg = messages[0]
            start_idx = 1
            sys_len = sys_msg.get("token_count") if "token_count" in sys_msg else self.tokenizer.count_tokens(sys_msg["content"])
            
        if sys_len >= max_in:
            # System prompt alone exceeds the budget, truncate it and return
            truncated_content = self._truncate_text_to_len(sys_msg["content"], max_in)
            return [{"role": "system", "content": truncated_content}]
            
        budget = max_in - sys_len
        kept_messages = []
        accumulated_len = 0
        
        # 2. Iterate in reverse over the non-system messages
        for msg in reversed(messages[start_idx:]):
            msg_len = msg.get("token_count") if "token_count" in msg else self.tokenizer.count_tokens(msg["content"])
            if accumulated_len + msg_len <= budget:
                kept_messages.insert(0, msg)
                accumulated_len += msg_len
            else:
                # Fill the remaining budget with a truncated version of the current message
                remaining_budget = budget - accumulated_len
                if remaining_budget > 0:
                    truncated_content = self._truncate_text_to_len(msg["content"], remaining_budget)
                    kept_messages.insert(0, {"role": msg["role"], "content": truncated_content})
                break
                
        # Strip token_count field from dicts to return standard {"role", "content"}
        final_messages = []
        if sys_msg:
            final_messages.append({"role": sys_msg["role"], "content": sys_msg["content"]})
        for m in kept_messages:
            final_messages.append({"role": m["role"], "content": m["content"]})
            
        return final_messages

    def _reconstruct_raw_calls(self, trace: WekaTrace) -> Tuple[List[RawCall], Optional[ReplaySessionEvent]]:
        # Reset local cache for deterministic scope
        self._cache.clear()
        self._hash_id_rng.set_trace_id(trace.id)

        # Build model mappings
        model_map = self._build_model_map(trace)

        # Build Plans
        normals: List[Tuple[int, Union[WekaNormalRequest, WekaStreamingRequest]]] = []
        subagents: List[Tuple[int, WekaSubagentEntry]] = []
        for idx, req in enumerate(trace.requests):
            if isinstance(req, WekaNormalRequest | WekaStreamingRequest):
                normals.append((idx, req))
            elif isinstance(req, WekaSubagentEntry):
                subagents.append((idx, req))

        preamble, detect_normals = _split_off_preamble(normals)
        if preamble:
            normals = sorted(preamble + detect_normals, key=lambda item: (item[1].t if hasattr(item[1], "t") and item[1].t is not None else 0, item[0]))

        trace_bs = self.weka_config.default_block_size
        if hasattr(trace, "block_size") and trace.block_size:
            trace_bs = trace.block_size

        # Resolve warmup start turn
        max_start = len(normals) - 1
        start_k = 0
        if self.weka_config.warmup_snapshot_sampling and max_start > 0:
            rng = random.Random(self.base_seed + abs(hash(trace.id)))
            min_ratio = getattr(self.weka_config, "warmup_snapshot_min_ratio", 0.25)
            max_ratio = getattr(self.weka_config, "warmup_snapshot_max_ratio", 0.75)
            ratio = rng.uniform(min_ratio, max_ratio)
            start_k = int(ratio * len(normals))
            start_k = max(0, min(start_k, max_start))
            logger.info(
                f"Trace {trace.id}: warmup snapshot sampling chose turn {start_k} (ratio {ratio:.3f}, out of {max_start})"
            )
        elif self.weka_config.start_turn_index is not None:
            start_k = min(self.weka_config.start_turn_index, max_start)
            logger.info(f"Trace {trace.id}: start_turn_index config chose turn {start_k} (out of {max_start})")

        first_parent_request_idx = normals[start_k][0] if normals else 0

        parent_plan = _ParentPlan(trace.id, normals, subagents, block_size=trace_bs)

        child_plans: List[_ChildPlan] = []
        for _sa_index, (sa_idx, entry) in enumerate(subagents):
            if sa_idx < first_parent_request_idx:
                logger.debug(
                    f"Trace {trace.id}: pruning subagent {entry.agent_id} spawned at request index {sa_idx} prior to start turn {start_k}"
                )
                continue
            streams = _pack_into_streams(list(entry.requests))
            if not streams:
                streams = [[]]
            multi = len(streams) > 1
            for stream_idx, stream_reqs in enumerate(streams):
                child_sid = f"{trace.id}::sa:{entry.agent_id}"
                if multi:
                    child_sid += f":s{stream_idx}"
                child_plans.append(
                    _ChildPlan(
                        session_id=child_sid,
                        parent_trace_id=trace.id,
                        subagent_index=sa_idx,
                        entry=entry,
                        stream_index=stream_idx,
                        stream_requests=stream_reqs,
                        block_size=trace_bs,
                    )
                )

        # Time warping
        timing = _build_trace_idle_timing(parent_plan, child_plans, self.weka_config.trace_idle_gap_cap_seconds)

        # Call reconstruction helper closures
        def decode_block_tokens(hash_ids: List[int]) -> List[int]:
            tokens: List[int] = []
            for h in hash_ids:
                cached = self._cache.get(h)
                if cached is None:
                    self._hash_id_rng.reseed_for_hash_id(h)
                    start = self._hash_id_rng.randrange(self._corpus_size)
                    end = start + trace_bs
                    cached = self._tokenized_corpus[start:end]
                    if end > self._corpus_size:
                        cached = cached + self._tokenized_corpus[: end - self._corpus_size]
                    self._cache[h] = cached
                tokens.extend(cached)
            return tokens

        def sample_partial_tail_tokens(n: int, seed: str) -> List[int]:
            if n <= 0:
                return []
            digest = hashlib.sha256(seed.encode()).digest()
            offset = int.from_bytes(digest[:8], "big") % max(self._corpus_size - n, 1)
            return list(self._tokenized_corpus[offset : offset + n])

        assert self.tokenizer is not None
        tokenizer_instance = self.tokenizer

        def decode_tokens_to_text(tokens: List[int]) -> str:
            decoded = tokenizer_instance.get_tokenizer().decode(tokens)
            return decoded if isinstance(decoded, str) else " ".join(decoded)

        # Reconstruct Parent Calls
        parent_recon = ConversationReconstructor(
            block_size=trace_bs,
            decode_block_tokens=decode_block_tokens,
            sample_partial_tail_tokens=sample_partial_tail_tokens,
            decode_tokens_to_text=decode_tokens_to_text,
            count_tokens=tokenizer_instance.count_tokens,
        )

        # Warm up the reconstructor state with pruned turns
        for k in range(start_k):
            req = parent_plan.normals[k][1]
            seed = f"{trace.id}:turn_{k}:partial_tail"
            if k == 0:
                parent_recon.init_turn_0(
                    hash_ids=req.hash_ids,
                    in_tokens=req.input_length,
                    tool_tokens=trace.tool_tokens,
                    system_tokens=trace.system_tokens,
                    seed=seed,
                )
            else:
                prev_req = parent_plan.normals[k - 1][1]
                parent_recon.advance_turn(
                    prev_hash_ids=prev_req.hash_ids,
                    prev_in_tokens=prev_req.input_length,
                    prev_out_tokens=prev_req.output_length,
                    curr_hash_ids=req.hash_ids,
                    curr_in_tokens=req.input_length,
                    seed=seed,
                )

        warmup_event = None
        if self.weka_config.warmup_cache_priming and start_k > 0:
            messages_dicts = parent_recon.snapshot_messages()
            messages_dicts = self._clamp_messages_to_model_limit(messages_dicts, max_out=1)
            warmup_event = ReplaySessionEvent(
                call_id=f"sa_warmup_{trace.id}_turn_{start_k - 1}",
                event_id=f"warmup:{trace.id}",
                session_index=-1,
                t_start_ms=0,
                t_end_ms=1000,
                model=model_map.get(parent_plan.normals[start_k - 1][1].model, parent_plan.normals[start_k - 1][1].model),
                messages=messages_dicts,
                expected_output="warmup",
                input_segments=[],
                expected_output_tokens=1,
                temperature=0.0,
                max_tokens_recorded=1,
            )

        parent_calls: List[RawCall] = []
        for k in range(start_k, len(parent_plan.normals)):
            outer_idx, req = parent_plan.normals[k]
            seed = f"{trace.id}:turn_{k}:partial_tail"
            if k == 0:
                parent_recon.init_turn_0(
                    hash_ids=req.hash_ids,
                    in_tokens=req.input_length,
                    tool_tokens=trace.tool_tokens,
                    system_tokens=trace.system_tokens,
                    seed=seed,
                )
            else:
                prev_req = parent_plan.normals[k - 1][1]
                parent_recon.advance_turn(
                    prev_hash_ids=prev_req.hash_ids,
                    prev_in_tokens=prev_req.input_length,
                    prev_out_tokens=prev_req.output_length,
                    curr_hash_ids=req.hash_ids,
                    curr_in_tokens=req.input_length,
                    seed=seed,
                )

            # Retrieve text messages for the prompt
            messages_dicts = parent_recon.snapshot_messages()
            messages_dicts = self._clamp_messages_to_model_limit(messages_dicts, max_out=req.output_length)
            messages = [ReplayMessage(role=m["role"], text=m["content"]) for m in messages_dicts]

            # Reconstruct timing
            t_timing = timing.parent_by_outer_idx[outer_idx]
            t_start_ms = int(t_timing.timestamp_seconds * 1000.0)
            t_end_ms = t_start_ms + int((req.api_time or 0.0) * 1000.0)

            # Completion is generated at next turn or placeholder if last turn
            expected_out_text = ""
            if k + 1 < len(parent_plan.normals):
                # Run lookahead advance to see what assistant message is generated
                lookahead = ConversationReconstructor(
                    block_size=trace_bs,
                    decode_block_tokens=decode_block_tokens,
                    sample_partial_tail_tokens=sample_partial_tail_tokens,
                    decode_tokens_to_text=decode_tokens_to_text,
                    count_tokens=tokenizer_instance.count_tokens,
                )
                lookahead._segments = [
                    RoleSegment(s.role, s.block_start, s.block_count, list(s.tokens), s.content, s.token_count)
                    for s in parent_recon._segments
                ]
                next_req = parent_plan.normals[k + 1][1]
                next_seed = f"{trace.id}:turn_{k + 1}:partial_tail"
                lookahead.advance_turn(
                    prev_hash_ids=req.hash_ids,
                    prev_in_tokens=req.input_length,
                    prev_out_tokens=req.output_length,
                    curr_hash_ids=next_req.hash_ids,
                    curr_in_tokens=next_req.input_length,
                    seed=next_seed,
                )
                # Find the assistant segment added
                for seg in reversed(lookahead._segments):
                    if seg.role == "assistant":
                        expected_out_text = seg.content
                        break
            else:
                # Last turn fallback: sample random tokens from corpus
                out_tokens = sample_partial_tail_tokens(req.output_length, f"{trace.id}:final_parent_turn_completion")
                expected_out_text = decode_tokens_to_text(out_tokens)

            out_msg = ReplayMessage(role="assistant", text=expected_out_text)

            parent_calls.append(
                RawCall(
                    call_id=f"parent_turn_{k}",
                    trace_id=trace.id,
                    t_start_ms=t_start_ms,
                    t_end_ms=t_end_ms,
                    model=model_map.get(req.model, req.model),
                    messages=messages,
                    out_message=out_msg,
                    prompt_tokens=req.input_length,
                    completion_tokens=req.output_length,
                    temperature=0.0,
                    max_tokens_recorded=req.output_length,
                    thread_id=trace.id,
                )
            )

        # Reconstruct Subagent Calls
        child_calls: List[RawCall] = []
        for cp in child_plans:
            child_recon = ConversationReconstructor(
                block_size=trace_bs,
                decode_block_tokens=decode_block_tokens,
                sample_partial_tail_tokens=sample_partial_tail_tokens,
                decode_tokens_to_text=decode_tokens_to_text,
                count_tokens=tokenizer_instance.count_tokens,
            )

            for k, creq in enumerate(cp.stream_requests):
                seed = f"{cp.session_id}:turn_{k}:partial_tail"
                if k == 0:
                    child_recon.init_turn_0(
                        hash_ids=creq.hash_ids,
                        in_tokens=creq.input_length,
                        tool_tokens=cp.entry.tool_tokens,
                        system_tokens=cp.entry.system_tokens,
                        seed=seed,
                    )
                else:
                    prev_creq = cp.stream_requests[k - 1]
                    child_recon.advance_turn(
                        prev_hash_ids=prev_creq.hash_ids,
                        prev_in_tokens=prev_creq.input_length,
                        prev_out_tokens=prev_creq.output_length,
                        curr_hash_ids=creq.hash_ids,
                        curr_in_tokens=creq.input_length,
                        seed=seed,
                    )

                messages_dicts = child_recon.snapshot_messages()
                messages_dicts = self._clamp_messages_to_model_limit(messages_dicts, max_out=creq.output_length)
                messages = [ReplayMessage(role=m["role"], text=m["content"]) for m in messages_dicts]

                t_timing = timing.child_by_session_request[(cp.session_id, k)]
                t_start_ms = int(t_timing.timestamp_seconds * 1000.0)
                t_end_ms = t_start_ms + int((creq.api_time or 0.0) * 1000.0)

                expected_out_text = ""
                if k + 1 < len(cp.stream_requests):
                    lookahead = ConversationReconstructor(
                        block_size=trace_bs,
                        decode_block_tokens=decode_block_tokens,
                        sample_partial_tail_tokens=sample_partial_tail_tokens,
                        decode_tokens_to_text=decode_tokens_to_text,
                        count_tokens=tokenizer_instance.count_tokens,
                    )
                    lookahead._segments = [
                        RoleSegment(s.role, s.block_start, s.block_count, list(s.tokens), s.content, s.token_count)
                        for s in child_recon._segments
                    ]
                    next_creq = cp.stream_requests[k + 1]
                    next_seed = f"{cp.session_id}:turn_{k + 1}:partial_tail"
                    lookahead.advance_turn(
                        prev_hash_ids=creq.hash_ids,
                        prev_in_tokens=creq.input_length,
                        prev_out_tokens=creq.output_length,
                        curr_hash_ids=next_creq.hash_ids,
                        curr_in_tokens=next_creq.input_length,
                        seed=next_seed,
                    )
                    for seg in reversed(lookahead._segments):
                        if seg.role == "assistant":
                            expected_out_text = seg.content
                            break
                else:
                    # Subagent final turn: lookahead to joining parent request
                    subagent_end_t = timing.subagent_end_by_outer_idx.get(cp.subagent_index)
                    joining_parent_req = None
                    joining_parent_idx = None
                    if subagent_end_t is not None:
                        for idx, (p_idx, p_req) in enumerate(parent_plan.normals):
                            p_timing = timing.parent_by_outer_idx.get(p_idx)
                            if p_timing and p_timing.timestamp_seconds >= subagent_end_t:
                                if all(h in p_req.hash_ids for h in creq.hash_ids):
                                    joining_parent_req = p_req
                                    joining_parent_idx = idx
                                    break

                    out_hashes = None
                    if joining_parent_req is not None and joining_parent_idx is not None:
                        parent_prev_req = parent_plan.normals[joining_parent_idx - 1][1] if joining_parent_idx > 0 else None
                        prev_hash_ids = parent_prev_req.hash_ids if parent_prev_req else []
                        curr_hash_ids = joining_parent_req.hash_ids
                        lcp = longest_common_prefix(prev_hash_ids, curr_hash_ids)
                        new_blocks = curr_hash_ids[lcp:]

                        sub_in = creq.hash_ids
                        idx_in_new = -1
                        for i in range(len(new_blocks) - len(sub_in) + 1):
                            if new_blocks[i : i + len(sub_in)] == sub_in:
                                idx_in_new = i
                                break

                        if idx_in_new >= 0:
                            asst_blocks = math.ceil(creq.output_length / trace_bs)
                            out_hashes = new_blocks[idx_in_new + len(sub_in) : idx_in_new + len(sub_in) + asst_blocks]

                    if out_hashes:
                        expected_out_text = decode_tokens_to_text(decode_block_tokens(out_hashes))
                    else:
                        out_tokens = sample_partial_tail_tokens(creq.output_length, f"{cp.session_id}:final_turn_completion")
                        expected_out_text = decode_tokens_to_text(out_tokens)

                out_msg = ReplayMessage(role="assistant", text=expected_out_text)

                child_calls.append(
                    RawCall(
                        # Call ID must match what build_graph uses, ensuring subagent uniqueness
                        call_id=f"sa_{cp.entry.agent_id}_s{cp.stream_index}_turn_{k}",
                        trace_id=trace.id,
                        t_start_ms=t_start_ms,
                        t_end_ms=t_end_ms,
                        model=model_map.get(creq.model, creq.model),
                        messages=messages,
                        out_message=out_msg,
                        prompt_tokens=creq.input_length,
                        completion_tokens=creq.output_length,
                        temperature=0.0,
                        max_tokens_recorded=creq.output_length,
                        thread_id=cp.session_id,
                    )
                )

        # Combine all parent and child calls, then sort chronologically
        all_calls = parent_calls + child_calls
        all_calls.sort(key=lambda c: (c.t_start_ms, c.call_id))
        return all_calls, warmup_event

    def _build_model_map(self, trace: WekaTrace) -> Dict[str, str]:
        """Maps trace-side models to configured api_config or target models."""
        configured = self.weka_config.model_mapping or {}
        if self.weka_config.use_static_model:
            return {m: self.weka_config.static_model_name for m in trace.models}
        return configured

    def _insert_warmup_event_into_graph(self, graph: ReplayGraph, warmup_event: ReplaySessionEvent) -> None:
        """Insert the warmup event directly into the session graph as the sole root node."""
        warmup_id = warmup_event.event_id

        # Calculate total input tokens (estimate from messages)
        total_input_tokens = sum(len(msg.get("content", "")) // 4 for msg in warmup_event.messages)
        total_input_tokens = max(1, total_input_tokens)

        input_segments = [
            InputSegment(
                type="unique",
                message_count=len(warmup_event.messages),
                token_count=total_input_tokens,
            )
        ]

        graph_call = GraphCall(
            call_id=warmup_event.call_id,
            model=warmup_event.model if hasattr(warmup_event, "model") else "",
            messages=warmup_event.messages,
            input_segments=input_segments,
            expected_output="warmup",
            expected_output_tokens=1,
            total_input_tokens=total_input_tokens,
            temperature=0.0,
            max_tokens_recorded=1,
        )

        graph_event = GraphEvent(
            event_id=warmup_id,
            call=graph_call,
            predecessor_event_ids=[],
            predecessor_dependency_types={},
            wait_ms=0,
            t_start_ms=0,
            t_end_ms=0,
        )

        # Add warmup event to graph.events
        graph.events[warmup_id] = graph_event

        # Update existing root events to depend on the warmup event
        for root_id in graph.root_event_ids:
            if root_id in graph.events:
                # Add warmup_id to predecessors of the root event
                graph.events[root_id].predecessor_event_ids.append(warmup_id)

        # Set graph.root_event_ids to contain ONLY the warmup event
        graph.root_event_ids = [warmup_id]
