apiVersion: batch/v1
kind: Job
metadata:
  name: inferencex-bench-5000qps
spec:
  template:
    spec:
      containers:
      - name: inferencex-bench
        image:  inferencex-bench:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        args:
        - "--backend"
        - "vllm"
        - "--host"
        - "vllm-llama3-8b-instruct-svc"
        - "--port"
        - "8000"
        - "--model"
        - "meta-llama/Llama-3.1-8B-Instruct"
        - "--dataset-name"
        - "random"
        - "--num-prompts"
        - "1500000"
        - "--request-rate"
        - "5000"
      restartPolicy: Never
  backoffLimit: 4
